# Generated by Django 6.0.2 on 2026-02-27 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stall_number', models.CharField(max_length=10, unique=True)),
                ('block', models.CharField(choices=[('A', 'Block A'), ('B', 'Block B'), ('C', 'Block C'), ('D', 'Block D')], max_length=1)),
                ('size', models.CharField(default='10x10 ft', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('pending', 'Pending Payment'), ('booked', 'Booked')], default='available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ExhibitorRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('representative_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('company_profile_link', models.URLField(blank=True, null=True)),
                ('products_featuring', models.TextField()),
                ('additional_support', models.TextField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('processing', 'Processing'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_bookings', to=settings.AUTH_USER_MODEL)),
                ('stall', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='exhibitions.stall')),
            ],
        ),
    ]
