# Generated by Django 6.0.2 on 2026-03-02 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitorregistration',
            name='approval_status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending_review', max_length=20),
        ),
        migrations.AddField(
            model_name='exhibitorregistration',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (visible in email to company)', null=True),
        ),
        migrations.AlterField(
            model_name='exhibitorregistration',
            name='stall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='exhibitions.stall'),
        ),
    ]
