# Generated by Django 6.0.2 on 2026-03-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0002_add_approval_status_and_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stall',
            name='block',
            field=models.CharField(blank=True, choices=[('A', 'Block A'), ('B', 'Block B'), ('C', 'Block C'), ('D', 'Block D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='stall',
            name='size',
            field=models.CharField(default='3x3 Mtr.', max_length=50),
        ),
    ]
