# Generated by Django 6.0.2 on 2026-03-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0003_make_block_nullable_resize_stall'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitorregistration',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Set automatically when admin approves. Payment deadline = approved_at + 24 h.', null=True),
        ),
    ]
