# Generated by Django 6.0.2 on 2026-03-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0004_add_approved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitorregistration',
            name='approval_status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired — Payment Deadline Missed')], db_index=True, default='pending_review', max_length=20),
        ),
    ]
